/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BalanceSheetRouteImport } from './routes/balance-sheet'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ImportRouteImport } from './routes/import'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PayRouteImport } from './routes/pay'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ProtectionRouteImport } from './routes/protection'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SpendingRouteImport } from './routes/spending'
import { Route as TenancyRouteImport } from './routes/tenancy'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ApiAdvisorChatRouteImport } from './routes/api/advisor/chat'
import { Route as ApiPublicBankLogoRouteImport } from './routes/api/public/bank-logo'
import { Route as ApiPublicHooksDocumentQueueRouteImport } from './routes/api/public/hooks/document-queue'
import { Route as ApiPublicHooksFxRefreshRouteImport } from './routes/api/public/hooks/fx-refresh'
import { Route as ApiPublicHooksImportQueueRouteImport } from './routes/api/public/hooks/import-queue'
import { Route as ApiPublicHooksMarketCloseRouteImport } from './routes/api/public/hooks/market-close'
import { Route as ApiPublicHooksNetWorthSnapshotRouteImport } from './routes/api/public/hooks/net-worth-snapshot'
import { Route as ApiPublicHooksWeeklyBriefingRouteImport } from './routes/api/public/hooks/weekly-briefing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BalanceSheetRoute = BalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectionRoute = ProtectionRouteImport.update({
  id: '/protection',
  path: '/protection',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendingRoute = SpendingRouteImport.update({
  id: '/spending',
  path: '/spending',
  getParentRoute: () => rootRouteImport,
} as any)
const TenancyRoute = TenancyRouteImport.update({
  id: '/tenancy',
  path: '/tenancy',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdvisorChatRoute = ApiAdvisorChatRouteImport.update({
  id: '/api/advisor/chat',
  path: '/api/advisor/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBankLogoRoute = ApiPublicBankLogoRouteImport.update({
  id: '/api/public/bank-logo',
  path: '/api/public/bank-logo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksDocumentQueueRoute =
  ApiPublicHooksDocumentQueueRouteImport.update({
    id: '/api/public/hooks/document-queue',
    path: '/api/public/hooks/document-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFxRefreshRoute = ApiPublicHooksFxRefreshRouteImport.update({
  id: '/api/public/hooks/fx-refresh',
  path: '/api/public/hooks/fx-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksImportQueueRoute =
  ApiPublicHooksImportQueueRouteImport.update({
    id: '/api/public/hooks/import-queue',
    path: '/api/public/hooks/import-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarketCloseRoute =
  ApiPublicHooksMarketCloseRouteImport.update({
    id: '/api/public/hooks/market-close',
    path: '/api/public/hooks/market-close',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNetWorthSnapshotRoute =
  ApiPublicHooksNetWorthSnapshotRouteImport.update({
    id: '/api/public/hooks/net-worth-snapshot',
    path: '/api/public/hooks/net-worth-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWeeklyBriefingRoute =
  ApiPublicHooksWeeklyBriefingRouteImport.update({
    id: '/api/public/hooks/weekly-briefing',
    path: '/api/public/hooks/weekly-briefing',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/documents': typeof DocumentsRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/planning': typeof PlanningRoute
  '/portfolio': typeof PortfolioRoute
  '/protection': typeof ProtectionRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/tenancy': typeof TenancyRoute
  '/transactions': typeof TransactionsRoute
  '/api/advisor/chat': typeof ApiAdvisorChatRoute
  '/api/public/bank-logo': typeof ApiPublicBankLogoRoute
  '/api/public/hooks/document-queue': typeof ApiPublicHooksDocumentQueueRoute
  '/api/public/hooks/fx-refresh': typeof ApiPublicHooksFxRefreshRoute
  '/api/public/hooks/import-queue': typeof ApiPublicHooksImportQueueRoute
  '/api/public/hooks/market-close': typeof ApiPublicHooksMarketCloseRoute
  '/api/public/hooks/net-worth-snapshot': typeof ApiPublicHooksNetWorthSnapshotRoute
  '/api/public/hooks/weekly-briefing': typeof ApiPublicHooksWeeklyBriefingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/documents': typeof DocumentsRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/planning': typeof PlanningRoute
  '/portfolio': typeof PortfolioRoute
  '/protection': typeof ProtectionRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/tenancy': typeof TenancyRoute
  '/transactions': typeof TransactionsRoute
  '/api/advisor/chat': typeof ApiAdvisorChatRoute
  '/api/public/bank-logo': typeof ApiPublicBankLogoRoute
  '/api/public/hooks/document-queue': typeof ApiPublicHooksDocumentQueueRoute
  '/api/public/hooks/fx-refresh': typeof ApiPublicHooksFxRefreshRoute
  '/api/public/hooks/import-queue': typeof ApiPublicHooksImportQueueRoute
  '/api/public/hooks/market-close': typeof ApiPublicHooksMarketCloseRoute
  '/api/public/hooks/net-worth-snapshot': typeof ApiPublicHooksNetWorthSnapshotRoute
  '/api/public/hooks/weekly-briefing': typeof ApiPublicHooksWeeklyBriefingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/advisor': typeof AdvisorRoute
  '/auth': typeof AuthRoute
  '/balance-sheet': typeof BalanceSheetRoute
  '/documents': typeof DocumentsRoute
  '/forecast': typeof ForecastRoute
  '/goals': typeof GoalsRoute
  '/import': typeof ImportRoute
  '/onboarding': typeof OnboardingRoute
  '/pay': typeof PayRoute
  '/planning': typeof PlanningRoute
  '/portfolio': typeof PortfolioRoute
  '/protection': typeof ProtectionRoute
  '/scenarios': typeof ScenariosRoute
  '/settings': typeof SettingsRoute
  '/spending': typeof SpendingRoute
  '/tenancy': typeof TenancyRoute
  '/transactions': typeof TransactionsRoute
  '/api/advisor/chat': typeof ApiAdvisorChatRoute
  '/api/public/bank-logo': typeof ApiPublicBankLogoRoute
  '/api/public/hooks/document-queue': typeof ApiPublicHooksDocumentQueueRoute
  '/api/public/hooks/fx-refresh': typeof ApiPublicHooksFxRefreshRoute
  '/api/public/hooks/import-queue': typeof ApiPublicHooksImportQueueRoute
  '/api/public/hooks/market-close': typeof ApiPublicHooksMarketCloseRoute
  '/api/public/hooks/net-worth-snapshot': typeof ApiPublicHooksNetWorthSnapshotRoute
  '/api/public/hooks/weekly-briefing': typeof ApiPublicHooksWeeklyBriefingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/advisor'
    | '/auth'
    | '/balance-sheet'
    | '/documents'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/onboarding'
    | '/pay'
    | '/planning'
    | '/portfolio'
    | '/protection'
    | '/scenarios'
    | '/settings'
    | '/spending'
    | '/tenancy'
    | '/transactions'
    | '/api/advisor/chat'
    | '/api/public/bank-logo'
    | '/api/public/hooks/document-queue'
    | '/api/public/hooks/fx-refresh'
    | '/api/public/hooks/import-queue'
    | '/api/public/hooks/market-close'
    | '/api/public/hooks/net-worth-snapshot'
    | '/api/public/hooks/weekly-briefing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/advisor'
    | '/auth'
    | '/balance-sheet'
    | '/documents'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/onboarding'
    | '/pay'
    | '/planning'
    | '/portfolio'
    | '/protection'
    | '/scenarios'
    | '/settings'
    | '/spending'
    | '/tenancy'
    | '/transactions'
    | '/api/advisor/chat'
    | '/api/public/bank-logo'
    | '/api/public/hooks/document-queue'
    | '/api/public/hooks/fx-refresh'
    | '/api/public/hooks/import-queue'
    | '/api/public/hooks/market-close'
    | '/api/public/hooks/net-worth-snapshot'
    | '/api/public/hooks/weekly-briefing'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/advisor'
    | '/auth'
    | '/balance-sheet'
    | '/documents'
    | '/forecast'
    | '/goals'
    | '/import'
    | '/onboarding'
    | '/pay'
    | '/planning'
    | '/portfolio'
    | '/protection'
    | '/scenarios'
    | '/settings'
    | '/spending'
    | '/tenancy'
    | '/transactions'
    | '/api/advisor/chat'
    | '/api/public/bank-logo'
    | '/api/public/hooks/document-queue'
    | '/api/public/hooks/fx-refresh'
    | '/api/public/hooks/import-queue'
    | '/api/public/hooks/market-close'
    | '/api/public/hooks/net-worth-snapshot'
    | '/api/public/hooks/weekly-briefing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AdvisorRoute: typeof AdvisorRoute
  AuthRoute: typeof AuthRoute
  BalanceSheetRoute: typeof BalanceSheetRoute
  DocumentsRoute: typeof DocumentsRoute
  ForecastRoute: typeof ForecastRoute
  GoalsRoute: typeof GoalsRoute
  ImportRoute: typeof ImportRoute
  OnboardingRoute: typeof OnboardingRoute
  PayRoute: typeof PayRoute
  PlanningRoute: typeof PlanningRoute
  PortfolioRoute: typeof PortfolioRoute
  ProtectionRoute: typeof ProtectionRoute
  ScenariosRoute: typeof ScenariosRoute
  SettingsRoute: typeof SettingsRoute
  SpendingRoute: typeof SpendingRoute
  TenancyRoute: typeof TenancyRoute
  TransactionsRoute: typeof TransactionsRoute
  ApiAdvisorChatRoute: typeof ApiAdvisorChatRoute
  ApiPublicBankLogoRoute: typeof ApiPublicBankLogoRoute
  ApiPublicHooksDocumentQueueRoute: typeof ApiPublicHooksDocumentQueueRoute
  ApiPublicHooksFxRefreshRoute: typeof ApiPublicHooksFxRefreshRoute
  ApiPublicHooksImportQueueRoute: typeof ApiPublicHooksImportQueueRoute
  ApiPublicHooksMarketCloseRoute: typeof ApiPublicHooksMarketCloseRoute
  ApiPublicHooksNetWorthSnapshotRoute: typeof ApiPublicHooksNetWorthSnapshotRoute
  ApiPublicHooksWeeklyBriefingRoute: typeof ApiPublicHooksWeeklyBriefingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balance-sheet': {
      id: '/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/balance-sheet'
      preLoaderRoute: typeof BalanceSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protection': {
      id: '/protection'
      path: '/protection'
      fullPath: '/protection'
      preLoaderRoute: typeof ProtectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spending': {
      id: '/spending'
      path: '/spending'
      fullPath: '/spending'
      preLoaderRoute: typeof SpendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenancy': {
      id: '/tenancy'
      path: '/tenancy'
      fullPath: '/tenancy'
      preLoaderRoute: typeof TenancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/advisor/chat': {
      id: '/api/advisor/chat'
      path: '/api/advisor/chat'
      fullPath: '/api/advisor/chat'
      preLoaderRoute: typeof ApiAdvisorChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bank-logo': {
      id: '/api/public/bank-logo'
      path: '/api/public/bank-logo'
      fullPath: '/api/public/bank-logo'
      preLoaderRoute: typeof ApiPublicBankLogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/document-queue': {
      id: '/api/public/hooks/document-queue'
      path: '/api/public/hooks/document-queue'
      fullPath: '/api/public/hooks/document-queue'
      preLoaderRoute: typeof ApiPublicHooksDocumentQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fx-refresh': {
      id: '/api/public/hooks/fx-refresh'
      path: '/api/public/hooks/fx-refresh'
      fullPath: '/api/public/hooks/fx-refresh'
      preLoaderRoute: typeof ApiPublicHooksFxRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/import-queue': {
      id: '/api/public/hooks/import-queue'
      path: '/api/public/hooks/import-queue'
      fullPath: '/api/public/hooks/import-queue'
      preLoaderRoute: typeof ApiPublicHooksImportQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/market-close': {
      id: '/api/public/hooks/market-close'
      path: '/api/public/hooks/market-close'
      fullPath: '/api/public/hooks/market-close'
      preLoaderRoute: typeof ApiPublicHooksMarketCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/net-worth-snapshot': {
      id: '/api/public/hooks/net-worth-snapshot'
      path: '/api/public/hooks/net-worth-snapshot'
      fullPath: '/api/public/hooks/net-worth-snapshot'
      preLoaderRoute: typeof ApiPublicHooksNetWorthSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-briefing': {
      id: '/api/public/hooks/weekly-briefing'
      path: '/api/public/hooks/weekly-briefing'
      fullPath: '/api/public/hooks/weekly-briefing'
      preLoaderRoute: typeof ApiPublicHooksWeeklyBriefingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AdvisorRoute: AdvisorRoute,
  AuthRoute: AuthRoute,
  BalanceSheetRoute: BalanceSheetRoute,
  DocumentsRoute: DocumentsRoute,
  ForecastRoute: ForecastRoute,
  GoalsRoute: GoalsRoute,
  ImportRoute: ImportRoute,
  OnboardingRoute: OnboardingRoute,
  PayRoute: PayRoute,
  PlanningRoute: PlanningRoute,
  PortfolioRoute: PortfolioRoute,
  ProtectionRoute: ProtectionRoute,
  ScenariosRoute: ScenariosRoute,
  SettingsRoute: SettingsRoute,
  SpendingRoute: SpendingRoute,
  TenancyRoute: TenancyRoute,
  TransactionsRoute: TransactionsRoute,
  ApiAdvisorChatRoute: ApiAdvisorChatRoute,
  ApiPublicBankLogoRoute: ApiPublicBankLogoRoute,
  ApiPublicHooksDocumentQueueRoute: ApiPublicHooksDocumentQueueRoute,
  ApiPublicHooksFxRefreshRoute: ApiPublicHooksFxRefreshRoute,
  ApiPublicHooksImportQueueRoute: ApiPublicHooksImportQueueRoute,
  ApiPublicHooksMarketCloseRoute: ApiPublicHooksMarketCloseRoute,
  ApiPublicHooksNetWorthSnapshotRoute: ApiPublicHooksNetWorthSnapshotRoute,
  ApiPublicHooksWeeklyBriefingRoute: ApiPublicHooksWeeklyBriefingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
